### ISSUE TITLE
地图任意切换

### ISSUE THREAD

**Issue by caopeng000** [pukaicom/MapLibForApp#1]
请问一下，你这种设计方案是不是可以实现地图任意切换的方案

**Comment by pukaicom** [comment]
这种设计方案其实是一种面向接口的典型设计，让业务层的调用不依赖于底层的具体实现而依赖于抽象的接口，所以如果你的app希望例如从高德地图切换到百度地图，其实是改动是很小的。而且一般来说app的一次运行周期都只会使用一种地图，我不太建议一个app里共存两种地图，毕竟从包体积的考虑，这样app显得太臃肿了
